# Generated by Django 5.2 on 2025-05-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In Exhibition", "In Exhibition"),
                            ("Sold", "Sold"),
                            ("Stored", "Stored"),
                        ],
                        max_length=20,
                    ),
                ),
                ("storage_location", models.CharField(max_length=200)),
            ],
        ),
    ]
